#define NULL_OBJECT_ID 0

#define NULL_USER_ID 0
#define SYSTEM_USER_ID 1
#define BANK_USER_ID 2
#define AGGREGATOR_ID 3

#define ACCOUNT_STATUS_ACTIVE 0
#define ACCOUNT_STATUS_FROZEN 1

#define JOURNAL_STATUS_IN_PROCESS -1
#define JOURNAL_STATUS_SUCCESS 0
#define JOURNAL_STATUS_ERROR 1
#define JOURNAL_STATUS_ROLLBACK 2

#define PAYMENT_STATUS_IN_PROCESS -1
#define PAYMENT_STATUS_SUCCESS 0
#define PAYMENT_STATUS_ERROR 1
#define PAYMENT_STATUS_NOT_ENOUGH_MONEY 2
#define PAYMENT_STATUS_ROLLBACK 3

#define WITHDRAW_STATUS_IN_PROCESS -1
#define WITHDRAW_STATUS_SUCCESS 0
#define WITHDRAW_STATUS_ERROR 1
#define WITHDRAW_STATUS_ROLLBACK 3

#define SECONDS_PER_DAY  86400
